### ISSUE TITLE
New revision (V1.2.0.0) build failed

### ISSUE THREAD

**Issue by jmafi** [pds-data-dictionaries/ldd-dawn#4]
I attempted a fairly major update to this dictionary, including correcting a number of XML validation errors in the existing version. The auto-run of the new version appeared to have failed in the LDDTool build phase, however, I'm not sure where to find the LDDTool logs to see if it's a problem with the ingest XML. I could use some help tracking down the problem.

**Comment by jstone-psi** [comment]
Hi, Joe,

You can access the build status through the actions tab.

The specific run that you are looking for is also at: https://github.com/pds-data-dictionaries/ldd-dawn/actions/runs/3324858939

It looks like the job that adds the logs (https://github.com/pds-data-dictionaries/ldd-dawn/actions/runs/3324858939/jobs/5496962669) is failing, along the LDDTool runner itself. This appears to be unrelated to the XML file.

I attempted to re-run the job, and it's still happening. This may be an issue with the build system.

**Comment by jstone-psi** [comment]
I tried building the LDD locally, and it seems to work fine there. However, I did notice that the structure of the repository is kind of unusual. The IngestLDD file should be directly under src/ and not in a versioned directory. That could be causing the problem, too.

**Comment by jmafi** [comment]
I tried moving the IngestLDD and re-committing, but it still fails at the same place. Thanks for the links. The log that I was looking for were the LDDTool logs referenced in line #227 of the "Generate Sub-Models" of the auto-validation and build process. That's where the build is failing.

**Comment by jstone-psi** [comment]
One other thing to try is renaming the ingest LDD. The other dictionaries follow a pattern of PDS4_NAMESPACE_IngestLDD.xml. And this is what the build system expects, as well.

**Comment by jmafi** [comment]
That fixed the problem! It now ran through and just failed on about 100 errors, but at least I have an error log and can make the needed corrections. Thanks so much for your help!
