### ISSUE TITLE
"Push SubMods and Logs to GitHub" failed

### ISSUE THREAD

**Issue by jmafi** [pds-data-dictionaries/ldd-dawn#5]
The error log indicates that the directory:

/home/runner/work/ldd-dawn/ldd-dawn/build/release/

does not exist. It appears that there is an unnecessary duplication of the "ldd-dawn" directory in this path, but it is not clear to me where or how to fix this problem or if it is in fact the problem.

**Comment by jordanpadams** [comment]
Resolved per https://github.com/pds-data-dictionaries/ldd-dawn/actions/runs/3482690073 and [aba861e](https://github.com/pds-data-dictionaries/ldd-dawn/commit/aba861ee4f8db7302a10686e3fbdce99ac56e7fc)
